version: '3.8'

services:
  api:
    build: .
    ports:
      - "4000:3000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app:/app/app  # For development hot reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Optional: Add a reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    profiles:
      - production